### ISSUE TITLE
Crash when creating a new world, with cobblestone as granular.

### ISSUE THREAD

**Issue by Priderino** [delvr/Repose#25] opened 2018-06-06 21:27 UTC
Forge: 14.23.4.2707
Farseek: 2.3
Repose: 1.6
Streams: 0.4.4

I tested it on my pack and i had crashes, but just to be sure, tried it on a clear instance, using only your mods, and the result was the same, apparently cobble doesn't like being made granular, since I had no problems with the default config, even on my pack.

Crash report: https://paste.ee/p/MsDNw
Config i'm using: https://pastebin.com/JLHi5Vpk

Modpack crash report: https://paste.ee/p/iqVUw
Modpack config: https://pastebin.com/BxurPxNc

**Comment by delvr** [comment] 2018-06-07 08:11
Thanks Priderino for reporting this! Looks like the latest Repose has a few regression bugs... :-( I'll take a look at this one and get back to you.

**Comment by nepphhh** [comment] 2018-06-14 14:23
Seconding this one.

**Comment by delvr** [comment] 2018-07-02 05:32
This is fixed in 1.6.1, please let me know of any issues.

**Closed as completed by delvr** 2018-07-02 05:32 UTC
Labels: bug, 1.12
