### ISSUE TITLE
[Bug] Sandstone block turned into dirt upon placing

### ISSUE THREAD

**Issue by CREEATION** [delvr/Repose#39] opened 2019-03-24 03:37 UTC
Hey,

I can't replicate the issue anymore, but is it possible that it's Repose related?
It was a regular vanilla sandstone block which just transformed into dirt when placed on the ground.
Placed like 10 blocks this way and suddenly, after placing other blocks, it didn't happen anymore.

There's nothing in the logs though.

**Comment by CREEATION** [comment] 2019-03-24 06:38
![mc_repose_bug](https://user-images.githubusercontent.com/3277769/54875934-d82bd680-4e07-11e9-9d32-58e5c30a2e0c.gif)

`repose.properties`:

```
# The blocks considered to be granular.
# Comma-separated list of values
repose.granularBlocks=atum:fertile_soil, atum:fertile_soil_tilled, atum:khnumite_raw, atum:limestone_gravel, atum:marl, atum:sand, minecraft:clay, minecraft:concrete_powder, minecraft:dirt, minecraft:farmland, minecraft:grass, minecraft:grass_path, minecraft:gravel, minecraft:mycelium, minecraft:sand, minecraft:soul_sand

# The blocks considered to be natural stone.
# Comma-separated list of values
repose.naturalStoneBlocks=atum:bone_ore, atum:coal_ore, atum:diamond_ore, atum:emerald_ore, atum:gold_ore, atum:iron_ore, atum:lapis_ore, atum:limestone, atum:redstone_ore, atum:relic_ore, minecraft:bedrock, minecraft:coal_ore, minecraft:diamond_ore, minecraft:emerald_ore, minecraft:end_stone, minecraft:gold_ore, minecraft:hardened_clay, minecraft:iron_ore, minecraft:lapis_ore, minecraft:netherrack, minecraft:quartz_ore, minecraft:red_sandstone, minecraft:redstone_ore, minecraft:sandstone, minecraft:stained_hardened_clay, minecraft:stone

# Makes certain blocks act as walkable slopes.
# Valid values: None, Granular Materials (default), Natural Stone Blocks, Both.
# [Granular Materials]: Clay, Dirt, Farmland, Fertile Soil, Grass Block, Grass Path, Gravel, Limestone Gravel, Marl,
# Mycelium, Raw Khnumite, Sand, Soul Sand, Strange Sand, Tilled Fertile Soil, concretePowder
# [Natural Stone Blocks]: Bedrock, Bone Ore, Coal Ore, Diamond Ore, Emerald Ore, End Stone, Gold Ore, Iron Ore, Lapis
# Lazuli Ore, Lapis Ore, Limestone, Nether Quartz Ore, Netherrack, Red Sandstone, Redstone Ore, Relic Ore, Sandstone,
# Stained Terracotta, Stone, Terracotta
repose.slopingBlocks=Granular Materials

# If true, all blocks made of granular material (not just sand and gravel) can fall down.
repose.soilFall=true

# If true, blocks that fall will also spread into piles instead of forming columns.
repose.blockSpread=true

# If true, non-soil blocks that can spread will also trigger avalanches when disturbed. Note: this option has no effect
# when using the EnviroMine mod.
repose.avalanches=false
```

**Comment by delvr** [comment] 2019-04-08 04:51
That's a strange bug. Some specific blocks such as grass and farmland are set up to transform to dirt when they fall, but that certainly doesn't include sandstone! And it's not configurable behavior either. Perhaps it was caused by some interaction with another mod?

I'll close this one for now, but please let me know if you ever see this behavior happening consistently. Thanks!

**Closed as completed by delvr** 2019-04-08 04:51 UTC
